authors:
  rafael:
    name: Rafael        # Author name
    description: konosubakonoakua # Author description
    avatar: https://avatars.githubusercontent.com/u/42881610         # Author avatar
    slug: https://github.com/konosubakonoakua           # Author profile slug
    url: https://github.com/konosubakonoakua            # Author website URL
